issue-tracking: github
repo-type: github
commit-patterns:
  REGEX: '^(?<message>.+) \((?<issue>#\d+)\)$'
  REVERT: '^Revert \"(?<message>.+) \((?<issue>#\d+)\)\"$'
auto:
  REGEX: '^(?<type>\w+)\/(?<issue>([A-Z]+-\d+|\#\d+))?-?(?<message>.*)$'